service:
  name: mapapp

plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod

package:
  individually: true

custom:
  webpack:
    packager: 'yarn'
    excludeFiles: 'src/**/*.spec.ts'
    includeModules:
      forceExclude:
        - aws-sdk
  customDomain:
    domainName: mapapp.micah.motorcycles
    stage: prod
    basePath: ''
    certificateName: mapapp.micah.motorcycles
    createRoute53Record: false

envVars: &envVars
  MONGO_URL: ${s3:mapapp-secrets/MONGO_URL}
  S3_BACKUP_BUCKET: ${s3:mapapp-secrets/S3_BACKUP_BUCKET}
  SPOT_FEED_ID: ${s3:mapapp-secrets/SPOT_FEED_ID}

functions:
  persistSpot:
    handler: src/handlers/scheduled_persist_spot.handle
    environment:
      <<: *envVars
    events:
      - schedule:
        enabled: true
        rate: rate(30 minutes)
  hello:
    handler: src/handlers/hello.handle
    events:
      - http:
          method: get
          path: hello
