service:
  name: mapapp
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  persistSpot:
    handler: handler.scheduledPersistSpot
    events:
      - schedule:
        enabled: false
        rate: rate(5 minutes)
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
