service:
  name: mapapp

plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod

custom:
  customDomain:
    domainName: mapapp.micah.motorcycles
    stage: prod
    basePath: ''
    certificateName: mapapp.micah.motorcycles
    createRoute53Record: false

envVars: &envVars
  MONGO_URL: ${s3:mapapp-secrets/MONGO_URL}
  S3_BACKUP_BUCKET: ${s3:mapapp-secrets/S3_BACKUP_BUCKET}
  SPOT_FEED_ID: ${s3:mapapp-secrets/SPOT_FEED_ID}

functions:
  persistSpot:
    handler: handler.scheduledPersistSpot
    environment:
      <<: *envVars
    events:
      - schedule:
        enabled: true
        rate: rate(30 minutes)
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
