service:
  name: mapapp

plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::${s3:mapapp-secrets/S3_BACKUP_BUCKET}/*"


package:
  individually: true

custom:
  webpack:
    packager: "yarn"
    excludeFiles: "src/**/*.spec.ts"
    includeModules:
      forceExclude:
        - aws-sdk
  customDomain:
    domainName: mapapp.micah.motorcycles
    stage: prod
    basePath: ""
    certificateName: mapapp.micah.motorcycles
    createRoute53Record: false

envVars: &envVars
  MONGO_URL: ${s3:mapapp-secrets/MONGO_URL}
  S3_BACKUP_BUCKET: ${s3:mapapp-secrets/S3_BACKUP_BUCKET}
  SPOT_FEED_ID: ${s3:mapapp-secrets/SPOT_FEED_ID}

functions:
  mapData:
    handler: src/handlers/map_data.handle
    environment:
      <<: *envVars
    events:
      - http:
          method: get
          path: map_data
          cors: true
  persistSpot:
    handler: src/handlers/scheduled_persist_spot.handle
    environment:
      <<: *envVars
    events:
      - schedule: rate(30 minutes)
  realtimeTrack:
    handler: src/handlers/realtime_track.handle
    environment:
      <<: *envVars
    events:
      - http:
          method: get
          path: realtime_track
          cors: true
  hello:
    handler: src/handlers/hello.handle
    events:
      - http:
          method: get
          path: hello
